apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pra.fullname" . }}-secrets
  labels:
    {{- include "pra.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.database.user }}:{{ .Values.secrets.dbPassword }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  secret-key: {{ .Values.secrets.secretKey | quote }}
  rapidapi-key: {{ .Values.secrets.rapidapiKey | default "" | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | default "" | quote }}
