apiVersion: v2
name: pra
description: Product Recommendation and Deal Finder Application with GPT Integration
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: fablihamaliha
    email: your-email@example.com

keywords:
  - flask
  - skincare
  - recommendations
  - deals
  - gpt

home: https://github.com/fablihamaliha/PRA
sources:
  - https://github.com/fablihamaliha/PRA
